### ISSUE TITLE
Beta requires libhandy but does not define it in manifest

### ISSUE THREAD

**Issue by BrainBlasted** [flathub/com.github.bilelmoussaoui.Authenticator#11]
This prevents users from launching Authenticator:

```python
Traceback (most recent call last):
  File "/app/bin/authenticator", line 31, in <module>
    require_version("Handy", "0.0")
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available

```

**Comment by bilelmoussaoui** [comment]
Sorry for the long delay. I have fixed the issue now.

**Comment by kai3341** [comment]
No fix found:  
```
kai@asus-ux360c:~/Projects/Authenticator/build-aux$ authenticator 
Traceback (most recent call last):
  File "/usr/local/bin/authenticator", line 31, in <module>
    require_version("Handy", "0.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available
```
After manual installing it works

**Comment by orangebowlerhat** [comment]
I hit this same problem today, unable to launch Password Safe since an update. Installing libhandy0 produces an even longer stream of errors but no app.
